// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindUsbDevice() {
  return window['go']['main']['App']['FindUsbDevice']();
}

export function GetDeviceList(arg1) {
  return window['go']['main']['App']['GetDeviceList'](arg1);
}

export function GetLastPing(arg1) {
  return window['go']['main']['App']['GetLastPing'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function TryConfigure(arg1) {
  return window['go']['main']['App']['TryConfigure'](arg1);
}

export function TryLogin(arg1) {
  return window['go']['main']['App']['TryLogin'](arg1);
}
