// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function FindUsbDevice():Promise<string>;

export function GetDeviceList(arg1:number):Promise<Array<main.Device>>;

export function GetLastPing(arg1:string):Promise<time.Time>;

export function Greet(arg1:string):Promise<string>;

export function TryConfigure(arg1:main.DeviceConfigArgs):Promise<boolean>;

export function TryLogin(arg1:main.LoginArgs):Promise<main.User>;
