// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3);
}

export function FindUsbDevice() {
  return window['go']['main']['App']['FindUsbDevice']();
}

export function GetDeviceList(arg1) {
  return window['go']['main']['App']['GetDeviceList'](arg1);
}

export function GetLastPing(arg1) {
  return window['go']['main']['App']['GetLastPing'](arg1);
}

export function ResetPw(arg1) {
  return window['go']['main']['App']['ResetPw'](arg1);
}

export function SignIn(arg1, arg2) {
  return window['go']['main']['App']['SignIn'](arg1, arg2);
}

export function SignOut(arg1) {
  return window['go']['main']['App']['SignOut'](arg1);
}

export function TryConfigure(arg1) {
  return window['go']['main']['App']['TryConfigure'](arg1);
}
